# Postgres db

version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      -  ./data:/postgres
    ports:
      - 5432:5432
  
  adminer:
    container_name: adminer_pg
    image: adminer
    restart: always
    ports:
      - 8080:8080